swagger: "2.0"
info:
  description: "Spécification du service User"
  version: "1.0.0"
  title: "Contrat API UserService"
basePath: /api  
paths:
  /users:
    get:
      tags:
        - "getUsers"
      summary: "Récupérer liste des utilisateurs"
      description: "Description du service"
      operationId: "getUsers"
      consumes: []
      produces:
      - "application/json"
      responses:
        200:
          schema:
            $ref: "#/definitions/ListUserResponse"
          description: "Liste des utilisateurs"
definitions:
  ListUserResponse:
    type: "array"
    items:
      $ref: "#/definitions/User"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
  