management:
  trace:
    http:
      enabled: true
      include: request-headers,response-headers,cookie-headers,principal,time-taken,authorization-header,remote-address,session-id
      tracebody: true 
  endpoints:
    web:
      exposure:
        include: info,health,httptrace
  endpoint:
    jolokia:
      enabled: true
    health:
      show-details: ALWAYS
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    jdbc-url: jdbc:h2:mem:k8sDB
    username: root
    driverClassName: org.h2.Driver
    password: admin
    initialization-mode: embedded
    platform: h2
  profiles:
    active: dev 

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    fr.sma.bw.tests: TRACE
server:
  error:
    whitelabel:
      enabled: false